config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  resources :serials do
    member do
      get 'items'
      get 'solr'
    end
  end
  resources :geographic_locations do
    member do
      get 'items'
      get 'collections'
      get 'serials'
      get 'consolidate'
      post 'consolidate/review', to: 'geographic_locations#review_consolidation'
      post 'consolidate/perform', to: 'geographic_locations#perform_consolidation'
    end
    collection do
      get 'suggest', to: 'geographic_locations#suggest'
    end
  end
  resources :events
  resources :names do
    collection do
      get 'suggest', to: 'names#suggest'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # API-ish endpoints
  constraints(format: :json) do
    get 'oai_support/dump',       to: 'oai_support#dump',      as: 'oai_support_dump'
    get 'oai_support/deleted',    to: 'oai_support#deleted',   as: 'oai_support_deleted'
    get 'oai_support/metadata',   to: 'oai_support#metadata',  as: 'oai_support_metadata'
    get 'api/info',               to: 'api#info',              as: 'api_info'
    get 'api/hi_info',            to: 'api#hi_info',           as: 'api_hi_info'
    get 'api/tab_features',       to: 'api#tab_features',      as: 'api_tab_features'
    get 'api/carousel_features',  to: 'api#carousel_features', as: 'api_carousel_features'
  end

  # API v2
  namespace :api do
    namespace :v2 do
      constraints(format: :json) do
        get 'ok', to: 'base#ok'
        resources :items, only: %i[index show]
        resources :collections, only: %i[index show]
        resources :holding_institutions, only: %i[index show]
        resources :features, only: :index
        get 'collections/:collection/resource/:slug', to: 'collection_resources#show'
      end
    end
  end

  concern :searchable, Blacklight::Routes::Searchable.new
  concern :exportable, Blacklight::Routes::Exportable.new

  devise_for :users, path: 'auth', controllers: {
    invitations: 'invitations'
  }

  devise_scope :user do
    get 'auth/invitations', to: 'invitations#index'
  end

  resource :profile, only: %i[show edit], controller: 'profile' do
    collection do
      patch 'update', as: 'update'
    end
  end

  resources :repositories, :users, :subjects, :time_periods,
            :features, :projects

  resources :holding_institutions do
    member do
      get 'solr'
    end
  end

  resources :remediation_actions, except: %i[edit update] do
    member do
      post 'perform', to: 'remediation_actions#perform'
      get 'review', to: 'remediation_actions#review'
    end
  end

  resources :item_versions, only: [] do
    member do
      patch :restore
    end
  end

  resources :collections do
    resources :collection_resources
    member do
      post 'reindex_items'
      get 'solr'
    end
  end

  resources :items do
    resources :pages do
      delete :index, on: :collection, action: :destroy_all, as: :destroy_all
    end
    resources :item_versions, only: [] do
      member do
        get :diff, to: 'item_versions#diff'
        patch :rollback, to: 'item_versions#rollback'
      end
    end
    collection do
      delete 'multiple_destroy', constraints: { format: :json }
      post 'xml'
      get 'deleted'
    end
    member do
      get 'copy'
      get 'fulltext'
      get 'solr'
    end
  end
  get '/items/new_from_serial/:serial_id', to: 'items#new_from_serial', as: 'new_item_from_serial'


  resources :batches do
    member do
      post 'recreate', to: 'batches#recreate'
      post 'commit', to: 'batches#commit'
      get 'commit_form', to: 'batches#commit_form'
      get 'import', to: 'batches#import'
      get 'results', to: 'batches#results'
      post 'quick_page_ingest'
    end
    collection do
      get 'select', to: 'batches#select'
    end

    resources :batch_items do
      collection do
        post 'import', to: 'batch_items#import', constraints: { format: :json }
      end
    end

    resources :batch_imports, except: %i[edit update] do
      collection do
        get 'help'
      end
    end
  end

  resources :fulltext_ingests, except: %i[edit update]
  resources :marc_xml_imports, except: %i[edit update] do
    collection do
      delete 'destroy_records'
    end
  end
  resources :page_ingests, except: %i[edit update] do
    member do
      get 'source.json', to: 'page_ingests#source_json', as: 'source_json', defaults: { format: :json }
    end
  end

  get '/reports/:id', to: 'reports#show', as: 'report'
  get '/reports', to: 'reports#index', as: 'reports'

  resource :catalog, only: [:index], controller: 'catalog', constraints: { id: /.*/ } do
    concerns :searchable
    collection do
      get 'facets', to: 'catalog#facets'
    end
    get 'facet_values/:facet_field', to: 'catalog#all_facet_values', as: 'facet_values_csv', constraints: { format: :csv }
  end

  # Constraints used to include format: false, which Rails 6 doesn't like. Deleted for now
  resources :solr_documents, only: [:show], path: '/record', controller: 'catalog', constraints: { id: /.*/ } do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end

  resources :tools, only: %i[index] do
    collection do
      get :csv_import, to: 'tools#csv_import_tool'
      put :csv_import, to: 'tools#csv_import'
      get :csv_template
    end
  end

  mount Blacklight::Engine => '/'
  mount BlacklightAdvancedSearch::Engine => '/'

  # Resque Admin
  resque_constraint = lambda do |request|
    request.env['warden'].authenticate!(scope: :user)
  end
  constraints resque_constraint do
    mount Resque::Server.new => '/resque'
  end

  # Base Paths
  authenticated do
    root to: 'advanced#index', as: :authenticated_root
  end

  root to: redirect('auth/sign_in')

end

app/models/collection.rb
# represent a DLG Collection
class Collection < ApplicationRecord
  #region includes
  include Slugged
  include IndexFilterable
  if FeatureFlags.enabled?(:geolocations_solr)
    include GeolocationIndexable
  else
    include GeospatialIndexable
  end
  include GeospatialIndexable
  include Portable
  include CollectionValidations
  include Provenanced
  include HasGeolocations
  include HasEducatorResources
  include PgSearch::Model
  #endregion

  #region relationships
  has_many :items, dependent: :destroy
  has_many :public_items, -> { where public: true }, class_name: 'Item'
  has_many :dpla_items, -> { where dpla: true }, class_name: 'Item'
  has_many :batch_items, dependent: :nullify
  has_many :collection_resources, -> { order(position: :asc) }
  belongs_to :repository, counter_cache: true
  has_and_belongs_to_many :subjects
  has_and_belongs_to_many :time_periods
  has_and_belongs_to_many :users
  has_many :collection_geographic_locations, dependent: :destroy
  has_many_geographic_locations_through :collection_geographic_locations
  #endregion

  #region validations
  validates_presence_of :repository
  #endregion

  # region callbacks
  before_destroy :clear_from_other_collections
  before_save :update_record_id
  after_update :record_id_change_in_solr
  after_update :reindex_children
  after_save :reindex_holding_institutions
  before_destroy :save_holding_institution_ids
  after_destroy :reindex_holding_institutions_after_destroy
  #endregion

  #region uploader
  mount_uploader :sponsor_image, ImageUploader
  #endregion

  #region scopes
  scope :for_indexing, lambda { includes(:portals, :holding_institutions, :repository, :geographic_locations,
                                  :collection_resources)
   }
  scope :updated_since, lambda { |since| where('updated_at >= ?', since) }
  scope :are_public, -> { where(public: true) }
  scope :are_displayed, -> { are_public.includes(:repository).where(repositories: {public: true}) }
  scope :alphabetized, -> { order(display_title: :asc) }
  scope :in_portal, ->(portal_type) { includes(:portals).where(portals:{code: portal_type}) }
  scope :text_search, ->(query) { search_for query }

  scope :sorted_by, lambda { |sort_option|
    direction = /desc$/.match?(sort_option) ? 'desc' : 'asc'
    case sort_option.to_s
    when /^id/ then order "collections.id #{direction}"
    when /^slug/ then order "collections.slug #{direction}"
    when /^title/ then order "collections.display_title #{direction}"
    when /^items_count/ then order("collections.items_count #{direction}")
    when /^collection_resources_count/ then order("collections.collection_resources_count #{direction}")
    when /^created_at/ then order "collections.created_at #{direction}"
    when /^updated_at/ then order "collections.updated_at #{direction}"
    else
      raise(ArgumentError, "Invalid sort option: #{sort_option.inspect}")
    end
  }

  scope :public_state, lambda { |active|
    case active
    when 'yes' then where(public: true)
    when 'no' then where(public: false)
    when '' then next
    else
      raise(ArgumentError, "Invalid Active option: #{active}")
    end
  }

  scope :for_repository, lambda { |repository_id|
    where(repository_id: repository_id)
  }

  scope :field_match, -> (field, to_match) { where("'#{to_match.downcase}' = ANY (lower(collections.#{field}::text)::text[])") }
  scope :educator_resources, -> { field_match('dcterms_medium', 'instructional materials') }
  #endregion

  # region solr_fields
  searchable do

    string :class_name, stored: true do
      self.class
    end

    string :slug, stored: true
    string :record_id, stored: true

    # set empty proxy id field so sunspot knows about it
    # value is set prior to save
    # sunspot search will not work without this, but indexing will
    # see monkeypatch @ config/initializers/sunspot_indexer_id.rb
    string :sunspot_id, stored: true do
      ''
    end

    integer :repository_id do
      repository.id
    end

    string :repository_slug do
      repository.slug
    end

    string :thumbnail, stored: true do
      # TODO: use brad's thumb links for now
      "https://dlg.galileo.usg.edu/do-th:#{repository.slug}"
    end

    boolean :public
    boolean :display do
      display?
    end
    boolean :educator_resource do
      dcterms_medium.compact.map(&:downcase).include? 'instructional materials'
    end

    string :public, stored: true do
      public ? 'Yes' : 'No'
    end

    string :display, stored: true do
      display? ? 'Yes' : 'No'
    end

    string :repository_name, stored: true, multiple: true do
      repository_titles
    end

    string :portal_names, stored: true, multiple: true do
      portal_names
    end

    string :portals, stored: true, multiple: true do
      portal_codes
    end

    string(:institution_slug, stored: true, multiple: true) do
      institution_slugs
    end

    string :display_title, stored: true, as: 'display_title_display'
    string :short_description, stored: true, as: 'short_description_display'

    string :sensitive_content, as: 'sensitive_content_display', multiple: true

    # *_display (not indexed, stored, multivalued)
    string :dcterms_provenance,             as: 'dcterms_provenance_display',             multiple: true
    string :dcterms_type,                   as: 'dcterms_type_display',                   multiple: true
    string(:dcterms_spatial, as: 'dcterms_spatial_display', multiple: true) { geolocations_to_dcspatial }
    string :dcterms_title,                  as: 'dcterms_title_display',                  multiple: true
    string :dcterms_creator,                as: 'dcterms_creator_display',                multiple: true
    string :dcterms_contributor,            as: 'dcterms_contributor_display',            multiple: true
    string :dcterms_subject,                as: 'dcterms_subject_display',                multiple: true
    string :dcterms_description,            as: 'dcterms_description_display',            multiple: true
    string :dcterms_publisher,              as: 'dcterms_publisher_display',              multiple: true
    string :edm_is_shown_at,                as: 'edm_is_shown_at_display',                multiple: true
    string :edm_is_shown_by,                as: 'edm_is_shown_by_display',                multiple: true
    string :dcterms_identifier,             as: 'dcterms_identifier_display',             multiple: true
    string :dc_date,                        as: 'dc_date_display',                        multiple: true
    string :dcterms_temporal,               as: 'dcterms_temporal_display',               multiple: true
    string :dc_format,                      as: 'dc_format_display',                      multiple: true
    string :dcterms_is_part_of,             as: 'dcterms_is_part_of_display',             multiple: true
    string :dc_right,                       as: 'dc_right_display',                       multiple: true
    string :dcterms_rights_holder,          as: 'dcterms_rights_holder_display',          multiple: true
    string :dcterms_bibliographic_citation, as: 'dcterms_bibliographic_citation_display', multiple: true
    string :dlg_local_right,                as: 'dlg_local_right_display',                multiple: true
    string :dlg_subject_personal,           as: 'dlg_subject_personal_display',           multiple: true
    string :dc_relation,                    as: 'dc_relation_display',                    multiple: true
    string :dcterms_medium,                 as: 'dcterms_medium_display',                 multiple: true
    string :dcterms_extent,                 as: 'dcterms_extent_display',                 multiple: true
    string :dcterms_language,               as: 'dcterms_language_display',               multiple: true

    string(:educator_resource_mediums, stored: true, multiple: true)

    # special collection-only fields
    string :collection_provenance_facet, multiple: true, as: 'collection_provenance_facet' do
      holding_institution_names
    end
    string :collection_type_facet, multiple: true, as: 'collection_type_facet' do
      dcterms_type
    end
    string :collection_spatial_facet, multiple: true, as: 'collection_spatial_facet' do
      geolocations_to_dcspatial
    end

    # just stored content
    string :partner_homepage_url,   as: 'partner_homepage_url_display'
    string :homepage_text,          as: 'homepage_text_display'

    # Primary Search Fields (multivalued, indexed, stemming/tokenized)
    text :dc_date
    text :dcterms_title
    text :dcterms_creator
    text :dcterms_contributor
    text :dcterms_subject
    text :dcterms_description
    text :dcterms_publisher
    text :dcterms_temporal
    text(:dcterms_spatial){geolocations_to_dcspatial}
    text :dcterms_is_part_of
    text :edm_is_shown_at
    text :edm_is_shown_by
    text :dcterms_identifier
    text :dcterms_rights_holder
    text :dlg_subject_personal
    text :dcterms_provenance

    string :title, as: 'title' do
      dcterms_title.first ? dcterms_title.first : slug
    end

    # required for Blacklight - a single valued format field
    string :format, as: 'format' do
      dc_format.first ? dc_format.first : ''
    end

    # sort fields

    string :title_sort, as: 'title_sort' do
      dcterms_title.first ? dcterms_title.first.downcase.gsub(/^(an?|the)\b/, '') : ''
    end

    string :creator_sort, as: 'creator_sort' do
      dcterms_creator.first ? dcterms_creator.first.downcase.gsub(/^(an?|the)\b/, '') : ''
    end

    string :yyyy_mm_dd_sort, as: 'yyyy_mm_dd_sort' do
      IndexDates.index_yyyy_mm_dd_sort(dc_date)
    end

    integer :year, as: 'year', trie: true do
      DateIndexer.new.get_sort_year(dc_date)
    end

    # facet fields
    string(:year_facet, as: 'year_facet', multiple: true){ IndexDates.index_years(dc_date) }
    string :counties, as: 'counties_facet', multiple: true
    string :us_states, as: 'us_states_facet', multiple: true

app/controllers/api/v2/collections_controller.rb
module Api
  module V2
    # API v2 controller for Collections
    class CollectionsController < BaseController
      def index
        @collections = Collection.where public: true
        filter_collections_by_portal
        render json: @collections.page(params[:page])
                                 .per(params[:per_page])
      end

      def show
        collection = if record_id? params[:id]
                       Collection.find_by_record_id params[:id]
                     else
                       Collection.find params[:id]
                     end
        raise ActiveRecord::RecordNotFound unless collection && collection.public?

        render json: collection, include: {
          portals: {},
          collection_resources: { only: %i[slug title position use_external_link external_link] },
          holding_institutions: { only: %i[image display_name authorized_name] }
        }
      end

      private

      def record_id?(id)
        id =~ /^[a-z0-9-]+_[a-z0-9-]+$/
      end

      def filter_collections_by_portal
        return unless params[:portal]

        @collections = @collections.includes(:portals)
                                   .joins(:portals)
                                   .where(portals: { code: params[:portal] })
      end
    end
  end
end

app/helpers/collections_helper.rb
module CollectionsHelper
  def invalid_items_count(collection)
    collection.items.select { |i| !i.valid? }.count
  end

  def solr_items_count(collection)
    Item.search do
      with(:collection_id, collection.id)
      adjust_solr_params do |params|
        params[:q] = ''
      end
    end.total
  end
end

app/views/collections/_collection.html.erb
<tr>
  <td><%= link_to collection.id, collection_path(collection) %></td>
  <td><%= link_to collection.slug, collection_path(collection) %></td>
  <td><%= link_to collection.title, collection_path(collection) %></td>
  <td><%= boolean_check_icon collection.public %></td>
  <td><%= link_to(collection.repository.title, repository_path(collection.repository)) if collection.repository %></td>
  <td><%= portal_badges collection %></td>
  <td><%= link_to(collection.items_count, items_path('filterrific[for_collection]' => collection.id)) %></td>
  <td><%= link_to(collection.collection_resources_count, collection_collection_resources_path(collection))%></td>
  <td><%= display_date collection.created_at %></td>
  <td><%= time_ago_in_words collection.updated_at %> ago</td>
  <td><%= render partial: 'shared/entity_actions', locals: { base_path: collection_path(collection), edit_path: edit_collection_path(collection), entity: collection, show_bl: false } %></td>
</tr>

app/views/collections/_collections_table.html.erb
<table class="table table-sm table-hover">
  <thead>
  <tr>
    <th><%= dlg_sorting_link(@filterrific, :id, label: t('meta.defaults.labels.columns.id')) %></th>
    <th><%= dlg_sorting_link(@filterrific, :slug, label: t('meta.defaults.labels.columns.slug')) %></th>
    <th><%= dlg_sorting_link(@filterrific, :title, label: t('meta.defaults.labels.columns.title')) %></th>
    <th><%= t('meta.defaults.labels.columns.public') %></th>
    <th><%= t('meta.defaults.labels.columns.repository') %></th>
    <th><%= t('meta.defaults.labels.columns.portals') %></th>
    <th><%= dlg_sorting_link(@filterrific, :items_count, label:t('meta.defaults.labels.columns.items_count')) %></th>
    <th><%= dlg_sorting_link(@filterrific, :collection_resources_count, label:t('meta.defaults.labels.columns.resources'))  %></th>
    <th><%= dlg_sorting_link(@filterrific, :created_at, label: t('activerecord.attributes.item.created_at')) %></th>
    <th><%= dlg_sorting_link(@filterrific, :updated_at, label: t('activerecord.attributes.item.updated_at')) %></th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <%= render @collections %>
  </tbody>
</table>

app/views/collections/_form.html.erb
<%= bootstrap_form_for(@collection) do |f| %>

    <%= f.alert_message t('meta.defaults.messages.errors.invalid_on_save', entity: 'Collection') %>

    <%= f.text_field :slug %>

    <%= f.select :repository_id, @data[:repositories].collect { |r| [r.title, r.id] }, {} %>

    <%= f.text_field :display_title %>
    <%= f.text_area :short_description %>
    <%= meta_textarea @collection, :sensitive_content %>

    <%= f.form_group :public do %>
        <%= f.check_box :public %>
    <% end %>

    <%= f.text_field :partner_homepage_url %>
    <%= f.text_area :homepage_text %>

    <%= f.select :other_repositories, @data[:repositories].collect { |r| [r.title, r.id] }, { include_blank: true }, { multiple: true,  class: 'fancy-multiselect' } %>

    <%= f.select :portal_ids, @data[:portals].collect { |c| [c.name, c.id] }, { }, { multiple: true,  class: 'fancy-multiselect' } %>

    <%= render partial: 'shared/edit_dc_fields', locals: { entity: @collection, form: f } %>

    <%= render_geographic_location_edit_form f %>

    <%= f.collection_check_boxes :subject_ids, @data[:subjects], :id, :name %>
    <%= f.collection_check_boxes :time_period_ids, @data[:time_periods], :id, :name %>

    <%= f.text_area :sponsor_note %>
  <% if @collection.sponsor_image? %>
    <label><%= t('activerecord.attributes.collection.sponsor_image') %></label><br>
    <%= image_tag(@collection.sponsor_image.url, class: 'thumbnail') if @collection.sponsor_image.url %>
    <%= f.check_box :remove_sponsor_image, label: t('meta.defaults.labels.remove_image') %>
  <% else %>
    <%= f.file_field :sponsor_image %>
    <%= f.hidden_field :sponsor_image_cache %>
  <% end %>


  <%= f.primary I18n.t('meta.defaults.actions.save'), class: 'btn btn-primary fixed-save-button' %>

<% end %>

app/views/collections/_sort_and_filter.html.erb
<div class="well well-sm index-filter-area">
  <h5 class="panel-heading">
    <span class="float-right">
      <%= render_filterrific_spinner %>
    </span>
  </h5>
    <%= form_for_filterrific(@filterrific, html:{id:"filterrific_text_search", class: "form-horizontal"}) do |f| %>
    <div class="form-group row">
      <%= f.label :text_search, "Search", class: "col-md-2 col-form-label" %>
      <div class="col-md-10">
        <%= f.text_field :text_search, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :for_portals, "Portals", class: "col-md-2 col-form-label" %>
      <div class="col-md-10">
        <%= f.select(
              :for_portals, @filterrific.select_options[:portals],
              {include_blank: false},
              class: 'form-control fancy-multiselect', multiple: true)
        %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :for_repository, "Repository", class: "col-md-2 col-form-label" %>
      <div class="col-md-10">
        <%= f.select(
              :for_repository,
              @filterrific.select_options[:repositories],
              { label: t('meta.defaults.labels.filter.repository'), include_blank: '', class: 'form-control fancy-select' },
              { class: 'form-control fancy-select' })
        %>
      </div>
    </div>

    <div class="form-group row">
      <%= f.label :public_state, "Public", class: "col-md-2 col-form-label" %>
      <div class="col-md-10">
        <%= f.select(
              :public_state, @filterrific.select_options[:public_states], {},
              class: 'form-control custom-select')
        %>
      </div>
    </div>
    <%= f.submit 'Filter', class: 'btn btn-primary'%>

<% end %>
</div>

app/views/collections/edit.html.erb
<div class="row">
  <div class="col-sm-12 col-md-11">
    <%= content_for :title do %>
        Edit Collection
    <% end %>

    <%= content_for :subtitle do %>
        <%= @collection.display_title %>
    <% end %>

    <% breadcrumb :collection, @collection %>

    <%= render 'shared/search_results_nav' %>
    <%= render 'shared/record_floating_nav' %>

    <%= render 'form' %>
  </div>
  <div class="col-md-1">
    <%= render 'shared/record_floating_nav' %>
  </div>
</div>

app/views/collections/index.html.erb
<%= content_for :title do %>
    Collections
<% end %>

<%= content_for :subtitle do
    if params[:repository_id] && !params[:repository_id].blank?
      t('meta.defaults.labels.filtered_by_subtitle', title: @collections.first.repository.title) if @collections.first && @collections.first.repository
    else
      t('meta.defaults.labels.unfiltered_index_subtitle')
    end
  end
%>

<% breadcrumb :collections %>

<%= link_to t('meta.collection.actions.add'), new_collection_path, class: 'btn btn-primary' %>
<%= render partial:'shared/per_pager_pagy' %>

<br><br>

<%= render_collection_list %>

app/views/collections/new.html.erb
<div class="row">
  <div class="col-sm-12 col-md-11">
    <%= content_for :title do %>
        New Collection
    <% end %>

    <% breadcrumb :collection, @collection %>

    <%= render 'form' %>
  </div>
  <div class="col-md-1">
    <%= render 'shared/record_floating_nav' %>
  </div>
</div>

app/views/collections/show.html.erb
<%= content_for :title do %>
    Show Collection
<% end %>

<%= content_for :subtitle do %>
    <%= @collection.display_title %>
<% end %>

<% breadcrumb :collection, @collection %>

<div class="btn-group">
  <%= link_to t('meta.defaults.actions.edit'), edit_collection_path(@collection), class: 'btn btn-primary' %>
  <%= link_to t('meta.collection.actions.add_collection_resource'), collection_collection_resources_path(@collection), class: 'btn btn-primary' %>
  <%= link_to t('meta.collection.actions.xml'), '#xml' , class: 'btn btn-primary', data: { turbolinks: false } %>
  <%= link_to t('meta.collection.actions.manage_items'), items_path( { 'filterrific[for_collection]' => @collection.id } ) , class: 'btn btn-primary' %>
  <%= link_to t('meta.collection.actions.download_item_xml'), items_path( { 'filterrific[for_collection]' => @collection.id, format: :xml } ) , class: 'btn btn-primary' %>
  <%= link_to(t('meta.collection.actions.reindex_items'), reindex_items_collection_path( { collection_id: @collection.id } ),method: :post,  data: { confirm: t('meta.collection.actions.reindex_items_confirm') }, class: 'btn btn-primary') if current_user.super? %>
  <%= link_to t('meta.defaults.actions.blacklight_view'), solr_document_path(@collection.record_id), class: 'btn btn-primary' %>
  <%= link_to(t('meta.item.actions.solr'), solr_collection_path(@collection) , class: 'btn btn-primary') %>


</div>

<br><br>

<%= render 'shared/show_field', field_name: t('activerecord.attributes.collection.repository_id'), value: link_to(@collection.repository.title, @collection.repository) %>
<%= render 'shared/show_field', field_name: t('activerecord.attributes.collection.thumbnail'), value: (image_tag(@collection.holding_institution_image) if @collection.holding_institution_image) %>
<%= render 'shared/show_field', field_name: t('activerecord.attributes.collection.portal_ids'), value: portals_list(@collection) %>
<%= render 'shared/show_field', field_name: t('activerecord.attributes.collection.record_id'), value: @collection.record_id %>
<%= render 'shared/show_field', field_name: t('activerecord.attributes.collection.slug'), value: @collection.slug %>
<%= render 'shared/show_field', field_name: t('activerecord.attributes.collection.display_title'), value: @collection.display_title %>
<%= render 'shared/show_field', field_name: t('activerecord.attributes.collection.short_description'), value: find_urls_and_linkify(@collection.short_description) %>
<%= render 'shared/show_multivalued_field', field_name: t('activerecord.attributes.collection.sensitive_content'), values: @collection.sensitive_content %>
<%= render 'shared/show_field', field_name: t('activerecord.attributes.collection.partner_homepage_url'), value: @collection.partner_homepage_url %>
<%= render 'shared/show_field', field_name: t('activerecord.attributes.collection.homepage_text'), value: @collection.homepage_text %>
<%= render 'shared/show_field', field_name: t('activerecord.attributes.collection.public'), value: @collection.public %>

<%= render partial: 'shared/show_dc_fields', locals: { entity: @collection } %>
<%= render 'shared/show_field', field_name: t('activerecord.attributes.collection.geographic_location'), value: geographic_locations_list(@collection) %>

<%= render 'shared/show_field', field_name: t('activerecord.attributes.collection.sponsor_note'), value: @collection.sponsor_note %>
<%= render 'shared/show_field', field_name: t('activerecord.attributes.collection.sponsor_image'), value: (image_tag(@collection.sponsor_image.url) if @collection.sponsor_image.url)%>

<%= render 'shared/show_field', field_name: t('activerecord.attributes.collection.created_at'), value: display_date(@collection.created_at) %>
<%= render 'shared/show_field', field_name: t('activerecord.attributes.collection.updated_at'), value: display_date(@collection.updated_at) %>
<%= render 'shared/show_multivalued_field', field_name: t('meta.collection.labels.view.other_repositories'), values: entities_links_array(@collection.other_repos, 'title') %>
<%= render 'shared/show_multivalued_field', field_name: t('meta.collection.labels.view.subjects'), values: entities_links_array(@collection.subjects, 'name') %>
<%= render 'shared/show_multivalued_field', field_name: t('meta.collection.labels.view.time_periods'), values: entities_links_array(@collection.time_periods, 'name') %>

<a name="xml"></a>
<div class="panel panel-default mb-3">
  <div class="panel-heading">
    <strong><%= t('meta.collection.labels.view.xml')%></strong><%= link_to 'Select All', '#xml', { data: { container_id: 'record_xml', turbolinks: false }, class: 'select-element-text btn btn-xs btn-primary float-right' } %>
  </div>
  <div class="panel-body">
    <pre id="record_xml"><%= @collection.to_xml({ show_provenance: true, show_repository: true, show_spatial: true }) %></pre>
  </div>
</div>

app/views/collections/solr.html.erb
<%= content_for :title do %>
    Solr Representation
<% end %>

<%= content_for :subtitle do %>
    <%= @collection.display_title %>
<% end %>

<% breadcrumb :solr_collection, @collection %>

<br><br>

<%= render 'shared/show_field', field_name: t('meta.item.labels.view.solr'),
                                value: pretty_json(@collection.solr_stored_hash.to_json) %>