config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  resources :serials do
    member do
      get 'items'
      get 'solr'
    end
  end
  resources :geographic_locations do
    member do
      get 'items'
      get 'collections'
      get 'serials'
      get 'consolidate'
      post 'consolidate/review', to: 'geographic_locations#review_consolidation'
      post 'consolidate/perform', to: 'geographic_locations#perform_consolidation'
    end
    collection do
      get 'suggest', to: 'geographic_locations#suggest'
    end
  end
  resources :events
  resources :names do
    collection do
      get 'suggest', to: 'names#suggest'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # API-ish endpoints
  constraints(format: :json) do
    get 'oai_support/dump',       to: 'oai_support#dump',      as: 'oai_support_dump'
    get 'oai_support/deleted',    to: 'oai_support#deleted',   as: 'oai_support_deleted'
    get 'oai_support/metadata',   to: 'oai_support#metadata',  as: 'oai_support_metadata'
    get 'api/info',               to: 'api#info',              as: 'api_info'
    get 'api/hi_info',            to: 'api#hi_info',           as: 'api_hi_info'
    get 'api/tab_features',       to: 'api#tab_features',      as: 'api_tab_features'
    get 'api/carousel_features',  to: 'api#carousel_features', as: 'api_carousel_features'
  end

  # API v2
  namespace :api do
    namespace :v2 do
      constraints(format: :json) do
        get 'ok', to: 'base#ok'
        resources :items, only: %i[index show]
        resources :collections, only: %i[index show]
        resources :holding_institutions, only: %i[index show]
        resources :features, only: :index
        get 'collections/:collection/resource/:slug', to: 'collection_resources#show'
      end
    end
  end

  concern :searchable, Blacklight::Routes::Searchable.new
  concern :exportable, Blacklight::Routes::Exportable.new

  devise_for :users, path: 'auth', controllers: {
    invitations: 'invitations'
  }

  devise_scope :user do
    get 'auth/invitations', to: 'invitations#index'
  end

  resource :profile, only: %i[show edit], controller: 'profile' do
    collection do
      patch 'update', as: 'update'
    end
  end

  resources :repositories, :users, :subjects, :time_periods,
            :features, :projects

  resources :holding_institutions do
    member do
      get 'solr'
    end
  end

  resources :remediation_actions, except: %i[edit update] do
    member do
      post 'perform', to: 'remediation_actions#perform'
      get 'review', to: 'remediation_actions#review'
    end
  end

  resources :item_versions, only: [] do
    member do
      patch :restore
    end
  end

  resources :collections do
    resources :collection_resources
    member do
      post 'reindex_items'
      get 'solr'
    end
  end

  resources :items do
    resources :pages do
      delete :index, on: :collection, action: :destroy_all, as: :destroy_all
    end
    resources :item_versions, only: [] do
      member do
        get :diff, to: 'item_versions#diff'
        patch :rollback, to: 'item_versions#rollback'
      end
    end
    collection do
      delete 'multiple_destroy', constraints: { format: :json }
      post 'xml'
      get 'deleted'
    end
    member do
      get 'copy'
      get 'fulltext'
      get 'solr'
    end
  end
  get '/items/new_from_serial/:serial_id', to: 'items#new_from_serial', as: 'new_item_from_serial'


  resources :batches do
    member do
      post 'recreate', to: 'batches#recreate'
      post 'commit', to: 'batches#commit'
      get 'commit_form', to: 'batches#commit_form'
      get 'import', to: 'batches#import'
      get 'results', to: 'batches#results'
      post 'quick_page_ingest'
    end
    collection do
      get 'select', to: 'batches#select'
    end

    resources :batch_items do
      collection do
        post 'import', to: 'batch_items#import', constraints: { format: :json }
      end
    end

    resources :batch_imports, except: %i[edit update] do
      collection do
        get 'help'
      end
    end
  end

  resources :fulltext_ingests, except: %i[edit update]
  resources :marc_xml_imports, except: %i[edit update] do
    collection do
      delete 'destroy_records'
    end
  end
  resources :page_ingests, except: %i[edit update] do
    member do
      get 'source.json', to: 'page_ingests#source_json', as: 'source_json', defaults: { format: :json }
    end
  end

  get '/reports/:id', to: 'reports#show', as: 'report'
  get '/reports', to: 'reports#index', as: 'reports'

  resource :catalog, only: [:index], controller: 'catalog', constraints: { id: /.*/ } do
    concerns :searchable
    collection do
      get 'facets', to: 'catalog#facets'
    end
    get 'facet_values/:facet_field', to: 'catalog#all_facet_values', as: 'facet_values_csv', constraints: { format: :csv }
  end

  # Constraints used to include format: false, which Rails 6 doesn't like. Deleted for now
  resources :solr_documents, only: [:show], path: '/record', controller: 'catalog', constraints: { id: /.*/ } do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end

  resources :tools, only: %i[index] do
    collection do
      get :csv_import, to: 'tools#csv_import_tool'
      put :csv_import, to: 'tools#csv_import'
      get :csv_template
    end
  end

  mount Blacklight::Engine => '/'
  mount BlacklightAdvancedSearch::Engine => '/'

  # Resque Admin
  resque_constraint = lambda do |request|
    request.env['warden'].authenticate!(scope: :user)
  end
  constraints resque_constraint do
    mount Resque::Server.new => '/resque'
  end

  # Base Paths
  authenticated do
    root to: 'advanced#index', as: :authenticated_root
  end

  root to: redirect('auth/sign_in')

end

app/models/repository.rb
# represent a Repository
class Repository < ApplicationRecord
  #region includes
  include Slugged
  include Portable
  include IndexFilterable
  include PgSearch::Model
  #endregion

  #region relationships
  has_and_belongs_to_many :holding_institutions
  has_many :collections, dependent: :destroy
  has_many :items, through: :collections
  has_and_belongs_to_many :users
  #endregion

  # region callbacks
  after_update :reindex_child_values
  #endregion

  #region validations
  validates_presence_of :title
  validates_uniqueness_of :slug
  #endregion

  #region uploader
  mount_uploader :image, ImageUploader
  # endregion

  #region scopes
  scope :updated_since, lambda { |since| where('updated_at >= ?', since) }
  scope :are_public, -> { where(public: true) }

  scope :text_search, ->(query) do
    next if query.blank?
    search_for query
  end

  scope :sorted_by, lambda { |sort_option|
    direction = /desc$/.match?(sort_option) ? 'desc' : 'asc'
    case sort_option.to_s
    when /^id/ then order "repositories.id #{direction}"
    when /^slug/ then order "repositories.slug #{direction}"
    when /^title/ then order "repositories.title #{direction}"
    when /^public/ then order("repositories.public #{direction}")
    when /^collections_count/ then order("repositories.collections_count #{direction}")
    when /^created_at/ then order "repositories.created_at #{direction}"
    when /^updated_at/ then order "repositories.updated_at #{direction}"
    else
      raise(ArgumentError, "Invalid sort option: #{sort_option.inspect}")
    end
  }

  scope :public_state, lambda { |active|
    case active
    when 'yes' then where(public: true)
    when 'no' then where(public: false)
    when '' then next
    else
      raise(ArgumentError, "Invalid Active option: #{active}")
    end
  }
  # endregion

  #region Setup for pg_search and filterrific
  pg_search_scope :search_for,
                  against: [:slug, :title],
                  using: {
                    tsearch: {
                      dictionary: 'english',
                      prefix: true
                    }
                  }

  filterrific(
    default_filter_params: { sorted_by: 'updated_at_desc' },
    available_filters: %i[sorted_by text_search public_state for_portals]
  )
  #endregion

  #region class_methods
  def self.index_query_fields
    %w[].freeze
  end

  def self.options_for_select
    order(Arel.sql 'LOWER(title)').map { |r| [r.title_with_slug, r.id] }
  end

  def self.public_states
    [['Public or Not Public', ''], %w[Public yes], ['Not Public', 'no']]
  end
  #endregion

  #region public_methods
  def record_id
    slug
  end

  def display?
    public?
  end

  def title_public_state
    state = public ? 'Public' : 'Not Public'
    "#{title} (#{state})"
  end

  def title_with_slug
    "#{title} (#{slug})"
  end
  # endregion

  # region private_methods
  private

  def reindex_child_values
    if saved_change_to_slug? || saved_change_to_title? || saved_change_to_public?
      queue_reindex_collections
      queue_reindex_items
    end
    true
  end

  def queue_reindex_collections
    Resque.enqueue(Reindexer, 'Collection', collections.pluck(:id)) if collections.any?
  end

  def queue_reindex_items
    if items.any?
      Resque.enqueue(Reindexer, 'Item', items.pluck(:id))
      serial_ids = items.pluck(:serial_id).uniq.compact
      Resque.enqueue(Reindexer, 'Serial', serial_ids) if serial_ids.any?
    end
  end
  # endregion
end

app/controllers/repositories_controller.rb
# Controller action for Repository functionality, duh
class RepositoriesController < ApplicationController
  load_and_authorize_resource
  include ErrorHandling
  include Sorting
  include Filterable
  before_action :set_data, only: %i[index new create edit update]

  def index
    @filterrific = initialize_filterrific(
      Repository,
      params[:filterrific],
      select_options: {
        portals: Portal.options_for_select(use_code: true),
        public_states: Repository.public_states
      }
    )

    @pagy, @repositories = if current_user.super? || current_user.viewer?
                           pagy(@filterrific.find.includes(:portals), items: per_page_setting)
                         else
                           pagy(@filterrific.find.where(id: current_user.repository_ids).includes(:portals), items: per_page_setting)
                         end

    respond_to do |format|
      format.html
      format.js {
        render 'shared/filterrific/index'
      }
    end
  end

  def show; end

  def new
    @repository = Repository.new
  end

  def create
    @repository = Repository.new repository_params
    if @repository.save
      redirect_to repository_path(@repository), notice: I18n.t('meta.defaults.messages.success.created', entity: 'Repository')
    else
      render :new, alert: I18n.t('meta.defaults.messages.errors.not_created', entity: 'Repository')
    end
  end

  def edit; end

  def update
    if @repository.update(repository_params)
      redirect_to repository_path(@repository), notice: I18n.t('meta.defaults.messages.success.updated', entity: 'Repository')
    else
      render :edit, alert: I18n.t('meta.defaults.messages.errors.not_updated', entity: 'Repository')
    end
  rescue PortalError => e
    @repository.errors.add :portals, e.message
    render :edit, alert: I18n.t('meta.defaults.messages.errors.not_updated', entity: 'Repository')
  end

  def destroy
    @repository.destroy
    redirect_to repositories_path, notice: I18n.t('meta.defaults.messages.success.destroyed', entity: 'Repository')
  end

  private

  def set_data
    @data = {}
    @data[:portals] = Portal.all.order(:name)
  end

  def repository_params
    params
      .require(:repository)
      .permit(:slug, :title, :notes, :public, portal_ids: [])
  end

end

app/views/repositories/_form.html.erb
<%= bootstrap_form_for(@repository, inline_errors: false) do |f| %>
  <%= f.alert_message t('meta.defaults.messages.errors.invalid_on_save', entity: 'Repository') %>
  <%= f.text_field :slug %>
  <%= f.text_field :title %>
  <%= f.form_group :public do %>
      <%= f.check_box :public %>
  <% end %>
  <%= f.select :portal_ids, @data[:portals].collect { |c| [c.name, c.id] }, {}, { multiple: true,  class: 'fancy-multiselect' } %>
  <%= f.text_area :notes %>
  <%= f.primary 'Save' %>
<% end %>

app/views/repositories/_repositories_table.html.erb
<table class="table table-sm table-hover">
  <thead>
  <tr>
    <th><%= dlg_sorting_link(@filterrific, :id, label: t('meta.defaults.labels.columns.id')) %></th>
    <th><%= dlg_sorting_link(@filterrific, :slug, label: t('meta.defaults.labels.columns.slug')) %></th>
    <th><%= dlg_sorting_link(@filterrific, :title, label: t('meta.defaults.labels.columns.title')) %></th>
    <th><%= t('meta.defaults.labels.columns.public') %></th>
    <th><%= t('meta.defaults.labels.columns.portals') %></th>
    <th><%= dlg_sorting_link(@filterrific, :collections_count, label:t('meta.defaults.labels.columns.collections_count')) %></th>
    <th><%= dlg_sorting_link(@filterrific, :created_at, label: t('activerecord.attributes.item.created_at')) %></th>
    <th><%= dlg_sorting_link(@filterrific, :updated_at, label: t('activerecord.attributes.item.updated_at')) %></th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <%= render @repositories %>
  </tbody>
</table>

app/views/repositories/_repository.html.erb
<tr>
  <td><%= link_to repository.id, repository_path(repository) %></td>
  <td><%= link_to repository.slug, repository_path(repository) %></td>
  <td><%= link_to repository.title, repository_path(repository) %></td>
  <td><%= boolean_check_icon repository.public %></td>
  <td><%= portal_badges repository %></td>
  <td><%= link_to(repository.collections_count, collections_path('filterrific[for_repository]' => repository.id)) %></td>
  <td><%= display_date repository.created_at %></td>
  <td><%= time_ago_in_words repository.updated_at %> ago</td>
  <td><%= render partial: 'shared/entity_actions', locals: { base_path: repository_path(repository), edit_path: edit_repository_path(repository), entity: repository, show_bl: false } %></td>
</tr>

app/views/repositories/_sort_and_filter.html.erb
<div class="well well-sm index-filter-area">
  <h5 class="panel-heading">
    <span class="float-right">
      <%= render_filterrific_spinner %>
    </span>
  </h5>
    <%= form_for_filterrific(@filterrific, html:{id:"filterrific_text_search", class: "form-horizontal"}) do |f| %>
    <div class="form-group row">
      <%= f.label :text_search, "Search", class: "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= f.text_field :text_search, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :for_portals, "Portals", class: "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= f.select(
              :for_portals, @filterrific.select_options[:portals],
              {include_blank: false},
              class: 'form-control fancy-multiselect', multiple: true)
        %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :public_state, "Public", class: "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= f.select(
              :public_state, @filterrific.select_options[:public_states], {},
              class: 'form-control custom-select')
        %>
      </div>
    </div>
    <%= f.submit 'Filter', class: 'btn btn-primary'%>

<% end %>
</div>

app/views/repositories/edit.html.erb
<%= content_for :title do %>
    Edit Repository
<% end %>

<%= content_for :subtitle do %>
    <%= @repository.title %>
<% end %>

<% breadcrumb :repository, @repository %>

<%= render 'form' %>

app/views/repositories/index.html.erb
<%= content_for :title do %>
    Repositories
<% end %>

<%= content_for :subtitle do %>
    <%= t('meta.defaults.labels.unfiltered_index_subtitle') %>
<% end %>

<% breadcrumb :repositories %>

<%= link_to t('meta.repository.actions.add'), new_repository_path, class: 'btn btn-outline-secondary' %>
<%= render partial:'shared/per_pager_pagy'%>

<br><br>

<%= render partial: 'sort_and_filter', locals: { filterrific: @filterrific } %>

<%= render partial: 'shared/filterrific/list', locals: {
  pagy: @pagy,
  filterrific: @filterrific,
}%>

app/views/repositories/new.html.erb
<%= content_for :title do %>
    New Repository
<% end %>

<% breadcrumb :repository, @repository %>

<%= render 'form' %>

app/views/repositories/show.html.erb
<%= content_for :title do %>
    Show Repository
<% end %>

<%= content_for :subtitle do %>
    <%= @repository.title %>
<% end %>

<% breadcrumb :repository, @repository %>

<%= link_to t('meta.defaults.actions.edit'), edit_repository_path(@repository), class: 'btn btn-primary' %>

<br><br>

<%= render 'shared/show_field', field_name: t('activerecord.attributes.holding_institution.image'), value: (image_tag(@repository.image.url) if @repository&.image.url) %>

<%= render 'shared/show_field', field_name: t(:slug,              scope: [:activerecord, :attributes, :repository]), value: @repository.slug %>
<%= render 'shared/show_field', field_name: t(:portal_ids,        scope: [:activerecord, :attributes, :repository]), value: portals_list(@repository) %>
<%= render 'shared/show_field', field_name: t(:public,            scope: [:activerecord, :attributes, :repository]), value: @repository.public %>
<%= render 'shared/show_field', field_name: t(:title,             scope: [:activerecord, :attributes, :repository]), value: @repository.title %>
<%= render 'shared/show_field', field_name: t(:created_at,        scope: [:activerecord, :attributes, :repository]), value: @repository.created_at %>
<%= render 'shared/show_field', field_name: t(:updated_at,        scope: [:activerecord, :attributes, :repository]), value: @repository.updated_at %>
<%= render 'shared/show_multivalued_field', field_name: t('meta.repository.labels.columns.collections'), values: entities_links_array(@repository.collections, 'display_title') %>
<%= render 'shared/show_multivalued_field', field_name: t('meta.repository.labels.columns.holding_institutions'), values: entities_links_array(@repository.holding_institutions, 'authorized_name') %>