config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  resources :serials do
    member do
      get 'items'
      get 'solr'
    end
  end
  resources :geographic_locations do
    member do
      get 'items'
      get 'collections'
      get 'serials'
      get 'consolidate'
      post 'consolidate/review', to: 'geographic_locations#review_consolidation'
      post 'consolidate/perform', to: 'geographic_locations#perform_consolidation'
    end
    collection do
      get 'suggest', to: 'geographic_locations#suggest'
    end
  end
  resources :events
  resources :names do
    collection do
      get 'suggest', to: 'names#suggest'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # API-ish endpoints
  constraints(format: :json) do
    get 'oai_support/dump',       to: 'oai_support#dump',      as: 'oai_support_dump'
    get 'oai_support/deleted',    to: 'oai_support#deleted',   as: 'oai_support_deleted'
    get 'oai_support/metadata',   to: 'oai_support#metadata',  as: 'oai_support_metadata'
    get 'api/info',               to: 'api#info',              as: 'api_info'
    get 'api/hi_info',            to: 'api#hi_info',           as: 'api_hi_info'
    get 'api/tab_features',       to: 'api#tab_features',      as: 'api_tab_features'
    get 'api/carousel_features',  to: 'api#carousel_features', as: 'api_carousel_features'
  end

  # API v2
  namespace :api do
    namespace :v2 do
      constraints(format: :json) do
        get 'ok', to: 'base#ok'
        resources :items, only: %i[index show]
        resources :collections, only: %i[index show]
        resources :holding_institutions, only: %i[index show]
        resources :features, only: :index
        get 'collections/:collection/resource/:slug', to: 'collection_resources#show'
      end
    end
  end

  concern :searchable, Blacklight::Routes::Searchable.new
  concern :exportable, Blacklight::Routes::Exportable.new

  devise_for :users, path: 'auth', controllers: {
    invitations: 'invitations'
  }

  devise_scope :user do
    get 'auth/invitations', to: 'invitations#index'
  end

  resource :profile, only: %i[show edit], controller: 'profile' do
    collection do
      patch 'update', as: 'update'
    end
  end

  resources :repositories, :users, :subjects, :time_periods,
            :features, :projects

  resources :holding_institutions do
    member do
      get 'solr'
    end
  end

  resources :remediation_actions, except: %i[edit update] do
    member do
      post 'perform', to: 'remediation_actions#perform'
      get 'review', to: 'remediation_actions#review'
    end
  end

  resources :item_versions, only: [] do
    member do
      patch :restore
    end
  end

  resources :collections do
    resources :collection_resources
    member do
      post 'reindex_items'
      get 'solr'
    end
  end

  resources :items do
    resources :pages do
      delete :index, on: :collection, action: :destroy_all, as: :destroy_all
    end
    resources :item_versions, only: [] do
      member do
        get :diff, to: 'item_versions#diff'
        patch :rollback, to: 'item_versions#rollback'
      end
    end
    collection do
      delete 'multiple_destroy', constraints: { format: :json }
      post 'xml'
      get 'deleted'
    end
    member do
      get 'copy'
      get 'fulltext'
      get 'solr'
    end
  end
  get '/items/new_from_serial/:serial_id', to: 'items#new_from_serial', as: 'new_item_from_serial'


  resources :batches do
    member do
      post 'recreate', to: 'batches#recreate'
      post 'commit', to: 'batches#commit'
      get 'commit_form', to: 'batches#commit_form'
      get 'import', to: 'batches#import'
      get 'results', to: 'batches#results'
      post 'quick_page_ingest'
    end
    collection do
      get 'select', to: 'batches#select'
    end

    resources :batch_items do
      collection do
        post 'import', to: 'batch_items#import', constraints: { format: :json }
      end
    end

    resources :batch_imports, except: %i[edit update] do
      collection do
        get 'help'
      end
    end
  end

  resources :fulltext_ingests, except: %i[edit update]
  resources :marc_xml_imports, except: %i[edit update] do
    collection do
      delete 'destroy_records'
    end
  end
  resources :page_ingests, except: %i[edit update] do
    member do
      get 'source.json', to: 'page_ingests#source_json', as: 'source_json', defaults: { format: :json }
    end
  end

  get '/reports/:id', to: 'reports#show', as: 'report'
  get '/reports', to: 'reports#index', as: 'reports'

  resource :catalog, only: [:index], controller: 'catalog', constraints: { id: /.*/ } do
    concerns :searchable
    collection do
      get 'facets', to: 'catalog#facets'
    end
    get 'facet_values/:facet_field', to: 'catalog#all_facet_values', as: 'facet_values_csv', constraints: { format: :csv }
  end

  # Constraints used to include format: false, which Rails 6 doesn't like. Deleted for now
  resources :solr_documents, only: [:show], path: '/record', controller: 'catalog', constraints: { id: /.*/ } do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end

  resources :tools, only: %i[index] do
    collection do
      get :csv_import, to: 'tools#csv_import_tool'
      put :csv_import, to: 'tools#csv_import'
      get :csv_template
    end
  end

  mount Blacklight::Engine => '/'
  mount BlacklightAdvancedSearch::Engine => '/'

  # Resque Admin
  resque_constraint = lambda do |request|
    request.env['warden'].authenticate!(scope: :user)
  end
  constraints resque_constraint do
    mount Resque::Server.new => '/resque'
  end

  # Base Paths
  authenticated do
    root to: 'advanced#index', as: :authenticated_root
  end

  root to: redirect('auth/sign_in')

end

app/models/name.rb
# frozen_string_literal: true

class Name < ApplicationRecord
  #region includes
  include ApplicationHelper
  include IndexFilterable
  include Portable
  include PgSearch::Model
  include ActionView::Helpers
  #endregion

  #region callbacks
  before_validation :update_slugs, unless: :skip_before_validation?
  after_save :update_associated_items
  before_destroy :save_associated_item_ids # Needs to come before the dependent: :destroy in the item_names relationship below
  after_destroy :reindex_associated_items
  #endregion

  #region relationships
  has_many :item_names, dependent: :destroy # This dependent: :destroy creates a callback
  has_many :items, through: :item_names
  #endregion

  #region validations
  validates_presence_of :slug
  validates_presence_of :authoritative_name
  validates_presence_of :name_type
  validates_uniqueness_of :slug
  validates_uniqueness_of :legacy_slug, allow_blank: true
  validate :slugs_unique
  validate :allowed_name_types

  #endregion

  #region scopes
  scope :for_indexing, lambda {
  }
  scope :are_public, -> { where(public: true) }
  scope :text_search, ->(query) { where('id in (:matches)', matches: search_for(query).select(:id)) }

  scope :sorted_by, lambda { |sort_option|
    direction = /desc$/.match?(sort_option) ? 'desc' : 'asc'
    case sort_option.to_s
    when /^id/ then order "names.id #{direction}"
    when /^slug/ then order "names.slug #{direction}"
    when /^authoritative_name/ then order "names.authoritative_name #{direction}"
    when /^created_at/ then order "names.created_at #{direction}"
    when /^updated_at/ then order "names.updated_at #{direction}"
    else
      raise(ArgumentError, "Invalid sort option: #{sort_option.inspect}")
    end
  }

  scope :public_state, lambda { |active|
    case active
    when 'yes' then where(public: true)
    when 'no' then where(public: false)
    when '' then next
    else
      raise(ArgumentError, "Invalid Active option: #{active}")
    end
  }

  scope :for_name_type, lambda { |name_type|
    where(name_type: name_type)
  }

  scope :in_additional_slugs, ->(slugs) { where("additional_slugs::text[]          && ARRAY[:s]", s: slugs) }
  scope :in_slug,             ->(slugs) { where("string_to_array(slug, '^')        && ARRAY[:s]", s: slugs) }
  scope :in_legacy_slug,      ->(slugs) { where("string_to_array(legacy_slug, '^') && ARRAY[:s]", s: slugs) }

  #endregion

  #region Setup for pg_search and filterrific
  pg_search_scope :search_for,
                  against: [:slug, :legacy_slug, :additional_slugs, :authoritative_name,
                            :alternate_names_public, :alternate_names_not_public, :oclc_number],
                  using: {
                    tsearch: {
                      dictionary: 'english',
                      prefix: true
                    }
                  }

  filterrific(
    default_filter_params: { sorted_by: 'updated_at_desc' },
    available_filters: %i[sorted_by text_search public_state for_portals for_name_type]
  )
  #endregion

  #region class_methods
  def self.sort_options
    [
      ['Recently Created', 'created_at_desc'],
      ['Recently Updated', 'updated_at_desc']
    ]
  end

  def self.public_states
    [['Public or Not Public', ''], %w[Public yes], ['Not Public', 'no']]
  end

  # All name type codes
  # @return [Array]
  def self.name_type_codes
    %w[person corpent]
  end

  def self.name_types_for_menus
    [
      %w[Person person],
      ['Corporate Entity', 'corpent'],
    ]
  end

  def self.normalized(name)
    name.gsub(/[[:punct:]]/, ' ') # change punctuations to spaces
        .gsub(/[^ -~]/,      ' ') # change non-ascii to spaces
        .strip                    # strip leading/trailing spaces
        .gsub(/  */,         ' ') # collapse multiple spaces
        .gsub(/ /,           '_') # change spaces to underscores
        .downcase                 # lowercase
  end

  def self.lookup_hash
    name_hash = {}
    Name.all.each do |name|
      name_hash[name.authoritative_name.downcase] = name
    end
    name_hash
  end
  #endregion

  # region public methods
  # All view type codes
  # @return [Array]
  def allowed_name_types
    return if Name.name_type_codes.include? name_type

    errors.add(:name_type, " '#{name_type}' is not a permitted name_type. Allowed types: #{Name.name_type_codes.join(", ")}")
  end

  def display?
    public
  end

  def authoritative_name_for_sort
    authoritative_name.downcase.gsub(/[^a-z0-9 ]/, '').sub(/^(?:the |an |a )/, '')
  end

  def first_char
    first_char = authoritative_name_for_sort[0]
    if first_char.match(/^[0-9]$/)
      '0-9'
    else
      first_char.upcase
    end
  end

  def update_slugs
    return true unless authoritative_name_changed?
    return true if authoritative_name.blank?
    new_slug = Name.normalized authoritative_name
    # want to remove new_slug if it had previously been there:
    self.additional_slugs = ([slug, additional_slugs].flatten.uniq - [new_slug]).compact
    self.slug = new_slug
  end

  def skip_before_validation?(value = false)
    @skip_before_validation = @skip_before_validation ? @skip_before_validation : value
  end

  def authoritative_name_changed?
    checking = ["authoritative_name"]
    checking - changes.keys != checking
  end

  def slugs_unique
    slug_in_additional_slugs
    slug_in_legacy_slug
    additional_slugs_in_slug
    additional_slugs_in_additional_slugs
    additional_slugs_in_legacy_slug
    legacy_slug_in_slug
    legacy_slug_in_additional_slugs
    legacy_slug_in_these_additional_slugs
  end

  def slug_in_additional_slugs
    found = Name.in_additional_slugs(slug).where.not(id: id)
    return unless found.any?
    errors.add(:slug, "#{slug} not unique in #{t('activerecord.attributes.name.additional_slugs')}, e.g., see #{found.first.authoritative_name} (#{found.first.id})")
  end

  def slug_in_legacy_slug
    found = Name.where(legacy_slug: slug).where.not(id: id)
    return unless found.any?
    errors.add(:slug, "#{slug} not unique in #{t('activerecord.attributes.name.legacy_slug')}, e.g., see #{found.first.authoritative_name} (#{found.first.id})")
  end

  def additional_slugs_in_slug
    return unless Name.in_slug(additional_slugs).where.not(id: id).any?
    additional_slugs.each do |slug|
      found = Name.where(slug: slug).where.not(id: id)
      if found.any?
        errors.add(:additional_slugs, "#{slug} not unique in #{t('activerecord.attributes.name.slug')}, e.g., see: #{found.first.authoritative_name} (#{found.first.id})")
        break
      end
    end
  end

  def additional_slugs_in_additional_slugs
    return unless Name.in_additional_slugs(additional_slugs).where.not(id: id).any?
    additional_slugs.each do |slug|
      found = Name.where("additional_slugs @> ?", "{#{slug}}").where.not(id: id)
      if found.any?
        errors.add(:additional_slugs, "#{slug} not unique, e.g., see: #{found.first.authoritative_name} (#{found.first.id})")
        break
      end
    end
  end

  def additional_slugs_in_legacy_slug
    return unless Name.in_legacy_slug(additional_slugs).where.not(id: id).any?
    additional_slugs.each do |slug|
      found = Name.where(legacy_slug: slug).where.not(id: id)
      if found.any?
        errors.add(:additional_slugs, "#{slug} not unique in #{t('activerecord.attributes.name.legacy_slug')}, e.g., see: #{found.first.authoritative_name} (#{found.first.id})")
        break
      end
    end
  end

  def legacy_slug_in_slug
    found = Name.where(slug: legacy_slug).where.not(id: id)
    return unless found.any?
    errors.add(:legacy_slug, "#{legacy_slug} not unique in #{t('activerecord.attributes.name.slug')}, e.g., see #{found.first.authoritative_name} (#{found.first.id})")
  end

  def legacy_slug_in_additional_slugs
    found = Name.in_additional_slugs(legacy_slug).where.not(id: id)
    return unless found.any?
    errors.add(:legacy_slug, "#{legacy_slug} not unique in #{t('activerecord.attributes.name.additional_slugs')}, e.g., see #{found.first.authoritative_name} (#{found.first.id})")
  end

  def legacy_slug_in_these_additional_slugs
    return unless additional_slugs.include? legacy_slug
    errors.add(:additional_slugs, "contains #{t('activerecord.attributes.name.legacy_slug')}: #{legacy_slug}")
  end

  def all_slugs
    slugs = [slug]
    if self.respond_to?(:additional_slugs)
      slugs += additional_slugs
    end
    if self.respond_to?(:legacy_slug)
      slugs += [legacy_slug]
    end
    slugs.uniq
  end

  # note: these respond_to? calls can be simplified once the name migrations are in production
  def all_search_names
      [authoritative_name, alternate_names_public, alternate_names_not_public].flatten.uniq
  end

  def update_associated_items
    unless saved_changes.include? :authoritative_name
      Sunspot.index! items.for_indexing
      return
    end

    new_item_ids = matched_item_ids
    current_item_ids = items.pluck(:id)

    # Add new matched items
    item_ids_to_add = new_item_ids.difference current_item_ids
    matching_item_names = item_ids_to_add.map { |item_id| {item_id: item_id, name_id: self.id} }
    ItemName.import(matching_item_names, validate: false)

    # Remove unmatched items
    item_ids_to_remove = current_item_ids.difference new_item_ids
    ItemName.where(name_id: self.id, item_id: item_ids_to_remove).delete_all

    # Reindex newly associated and unmatched items
    item_ids_to_reindex = item_ids_to_add.union item_ids_to_remove
    Sunspot.index! Item.where(id: item_ids_to_reindex).for_indexing
  end

  def matched_item_ids
    Item.for_name(authoritative_name).pluck(:id)
  end

  def save_associated_item_ids
    @associated_item_ids = items.pluck(:id)
  end

  def reindex_associated_items
    Sunspot.index! Item.where(id: @associated_item_ids).for_indexing
  end

  # endregion

  #region solr_fields
  searchable do
    string(:class_name, stored: true) { self.class }
    # Blacklight 'Required' fields #

app/views/names/_alternate_name_fields.html.erb
<div class="nested-fields well">
  <%= f.text_field :alt_name %>
  <div class="nested-fields-options">
    <%= f.check_box :public %>
    <%= link_to_remove_association 'remove', f, class: 'btn btn-sm btn-danger' %>
  </div>
</div>

app/views/names/_form.html.erb
<%= bootstrap_form_for(@name) do |f| %>

  <%= f.alert_message t('meta.defaults.messages.errors.invalid_on_save', entity: 'Name') %>

  <%= render 'shared/show_field', field_name: t('activerecord.attributes.name.slug'), value: @name.slug %>

  <%= meta_textarea @name, :additional_slugs %>

  <%= f.text_field :legacy_slug %>

  <%= f.check_box :public %>

  <%= f.select :portal_ids, @data[:portals].collect { |c| [c.name, c.id] }, { }, { multiple: true,  class: 'fancy-multiselect' } %>

  <%= f.select(:name_type, Name.name_types_for_menus,
        { include_blank: false, class: 'form-control' },
        { class: 'form-control' })
  %>

  <%= f.text_field :authoritative_name %>

  <%= meta_textarea @name, :alternate_names_public %>

  <%= meta_textarea @name, :alternate_names_not_public %>

  <%= meta_textarea @name, :related_names %>

  <%= f.text_area :bio_history, class: 'fulltext-input' %>

  <%= meta_textarea @name, :authoritative_name_source %>

  <%= f.text_field :source_uri %>

  <%= f.text_field :oclc_number %>

  <%= f.primary t('meta.defaults.actions.save') %>

<% end %>

app/views/names/_list.html.erb
<div id="name-results">
  <div class="row">
    <div class="col-sm-6">
      <%= paginate @names %>
    </div>
    <div class="col-sm-6 text-right">
      <span class="badge badge-secondary"><%= @names.count %></span> records shown of <span class="badge badge-secondary"><%= @names.total_count %></span> total records
    </div>
  </div>
  <%= render 'names/names_table' %>
</div>

app/views/names/_name.html.erb
<tr>
  <td><%= link_to name.id, name %></td>
  <td><%= link_to name.slug, name %></td>
  <td><%= link_to name.authoritative_name, name %></td>
  <td><%= name.name_type %></td>
  <td><%= portal_badges name %></td>
  <td><%= name.public %></td>
  <td><%= display_date name.created_at %></td>
  <td><%= time_ago_in_words name.updated_at %> ago</td>
  <td>
    <div class="btn-group btn-group-sm">
      <%= link_to t('meta.defaults.actions.view'), name_path(name),
                  class: 'btn btn-outline-secondary' %>
      <%= link_to t('meta.defaults.actions.edit'), edit_name_path(name),
                  class: 'btn btn-outline-secondary' %>
      <%= link_to t('meta.defaults.actions.destroy'), name_path(name),
                  method: :delete,
                  data: { confirm: t('meta.defaults.labels.confirm') },
                  class: 'btn btn-outline-secondary' %>
    </div>
  </td>
</tr>

app/views/names/_names_table.html.erb
<table class="table table-sm table-hover">
  <thead>
  <tr>
    <th><%= dlg_sorting_link(@filterrific, :id, label: t('meta.defaults.labels.columns.id')) %></th>
    <th><%= dlg_sorting_link(@filterrific, :slug, label: t('meta.defaults.labels.columns.slug')) %></th>
    <th><%= dlg_sorting_link(@filterrific, :authoritative_name, label: t('activerecord.attributes.name.authoritative_name')) %></th>
    <th><%= t('activerecord.attributes.name.name_type') %></th>
    <th><%= t('meta.defaults.labels.columns.portals') %></th>
    <th><%= t('meta.defaults.labels.columns.public') %></th>
    <th><%= dlg_sorting_link(@filterrific, :created_at, label: t('activerecord.attributes.item.created_at')) %></th>
    <th><%= dlg_sorting_link(@filterrific, :updated_at, label: t('activerecord.attributes.item.updated_at')) %></th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <%= render @names %>
  </tbody>
</table>

app/views/names/_sort_and_filter.html.erb
<div class="well well-sm index-filter-area">
  <h5 class="panel-heading">
    <span class="float-right">
      <%= render_filterrific_spinner %>
    </span>
  </h5>
    <%= form_for_filterrific(@filterrific, html:{class: "form-horizontal"}) do |f| %>
    <div class="form-group row">
      <%= f.label :text_search, "Search", class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :text_search, class: 'form-control filterrific-periodically-observed' %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :public_state, "Name Type", class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.select(
              :for_name_type, @filterrific.select_options[:name_types],
              { include_blank: '', class: 'form-control fancy-select' },
              { class: 'form-control fancy-select' })
        %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :for_portals, "Portals", class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.select(
              :for_portals, @filterrific.select_options[:portals],
              {include_blank: false},
              class: 'form-control fancy-multiselect', multiple: true)
        %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :public_state, "Public", class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.select(
              :public_state, @filterrific.select_options[:public_states], {},
              class: 'form-control custom-select')
        %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :sorted_by, "Sort By", class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.select(
              :sorted_by, @filterrific.select_options[:sorted_by], {},
              class: 'form-control custom-select')
        %>
      </div>
    </div>
    <% end %>
</div>

app/views/names/edit.html.erb
<div class="row">
  <div class="col-sm-12 col-md-12">
    <%= content_for :title do %>
      Edit Name
    <% end %>

    <%= content_for :subtitle do %>
      <%= "#{@name.authoritative_name}" %>
    <% end %>

    <% breadcrumb :name, @name %>
    <%= render 'shared/search_results_nav' %>
    <%= render 'form' %>
  </div>
</div>

app/views/names/index.html.erb
<%= content_for :title do %>
  Names
<% end %>

<% breadcrumb :names %>

<%= link_to t('meta.name.action.add'), new_name_path, class: 'btn btn-outline-secondary' %>

<%= render 'shared/per_pager' %>

<br><br>

<%= render partial: 'sort_and_filter', locals: {
  names: @names, filterrific: @filterrific
} %>

<%= render partial: 'list', locals: {
  names: @names,
  filterrific: @filterrific
} %>

app/views/names/index.js.erb
<% js = escape_javascript(
render(partial: 'list')
) %>
$("#name-results").html("<%= js %>");

app/views/names/new.html.erb
<%= content_for :title do %>
  New Name
<% end %>

<% breadcrumb :name, @name %>

<%= render 'form' %>

app/views/names/show.html.erb
<%= content_for :title do %>
  Show Name
<% end %>

<%= content_for :subtitle do %>
  <%= @name.authoritative_name %>
<% end %>

<% breadcrumb :name, @name %>

<div class="btn-group" role="group" aria-label="Name actions">
  <%= link_to t('meta.defaults.actions.edit'), edit_name_path(@name), class: 'btn btn-primary' %>
</div>

<br><br>

<%= render 'shared/show_field', field_name: t('activerecord.attributes.name.slug'), value: @name.slug %>
<%= render 'shared/show_multivalued_field', field_name: t('activerecord.attributes.name.additional_slugs'), values: @name.additional_slugs %>
<%= render 'shared/show_field', field_name: t('activerecord.attributes.name.legacy_slug'), value: @name.legacy_slug %>
<%= render 'shared/show_field', field_name: t('activerecord.attributes.name.name_type'), value: @name.name_type %>
<%= render 'shared/show_field', field_name: t('activerecord.attributes.name.authoritative_name'), value: @name.authoritative_name %>

<%= render 'shared/show_multivalued_field', field_name: t('activerecord.attributes.name.alternate_names_public'), values: @name.alternate_names_public %>
<%= render 'shared/show_multivalued_field', field_name: t('activerecord.attributes.name.alternate_names_not_public'), values: @name.alternate_names_not_public %>

<%= render 'shared/show_multivalued_field', field_name: t('activerecord.attributes.name.related_names'), values: @name.related_names %>
<%= render 'shared/show_field', field_name: t('activerecord.attributes.name.bio_history'), value: @name.bio_history %>
<%= render 'shared/show_multivalued_field', field_name: t('activerecord.attributes.name.authoritative_name_source'), values: @name.authoritative_name_source %>
<%= render 'shared/show_field', field_name: t('activerecord.attributes.name.source_uri'), value: @name.source_uri %>
<%= render 'shared/show_field', field_name: t('activerecord.attributes.name.public'), value: @name.public %>
<%= render 'shared/show_field', field_name: t('activerecord.attributes.name.portal_ids'), value: portals_list(@name) %>
<%= render 'shared/show_field', field_name: t('activerecord.attributes.name.oclc_number'), value: @name.oclc_number %>

<div class="panel panel-default mb-3">
  <div class="panel-heading">
    <strong><%= t('activerecord.attributes.name.item_ids') %></strong>
  </div>
  <div class="panel-body">
    <ol>
      <% @name.items.order(:record_id).each do |item| %>
        <li><%= link_to "#{item.record_id} | #{item.dcterms_title.first}", item %></li>
      <% end %>
    </ol>
  </div>
</div>

<%= render 'shared/show_field', field_name: t('activerecord.attributes.name.legacy_data'), value: pretty_json(@name.legacy_data) %>
<%= render 'shared/show_field', field_name: t('activerecord.attributes.name.created_at'), value: display_date(@name.created_at) %>
<%= render 'shared/show_field', field_name: t('activerecord.attributes.name.updated_at'), value: display_date(@name.updated_at) %>