config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  resources :serials do
    member do
      get 'items'
      get 'solr'
    end
  end
  resources :geographic_locations do
    member do
      get 'items'
      get 'collections'
      get 'serials'
      get 'consolidate'
      post 'consolidate/review', to: 'geographic_locations#review_consolidation'
      post 'consolidate/perform', to: 'geographic_locations#perform_consolidation'
    end
    collection do
      get 'suggest', to: 'geographic_locations#suggest'
    end
  end
  resources :events
  resources :names do
    collection do
      get 'suggest', to: 'names#suggest'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # API-ish endpoints
  constraints(format: :json) do
    get 'oai_support/dump',       to: 'oai_support#dump',      as: 'oai_support_dump'
    get 'oai_support/deleted',    to: 'oai_support#deleted',   as: 'oai_support_deleted'
    get 'oai_support/metadata',   to: 'oai_support#metadata',  as: 'oai_support_metadata'
    get 'api/info',               to: 'api#info',              as: 'api_info'
    get 'api/hi_info',            to: 'api#hi_info',           as: 'api_hi_info'
    get 'api/tab_features',       to: 'api#tab_features',      as: 'api_tab_features'
    get 'api/carousel_features',  to: 'api#carousel_features', as: 'api_carousel_features'
  end

  # API v2
  namespace :api do
    namespace :v2 do
      constraints(format: :json) do
        get 'ok', to: 'base#ok'
        resources :items, only: %i[index show]
        resources :collections, only: %i[index show]
        resources :holding_institutions, only: %i[index show]
        resources :features, only: :index
        get 'collections/:collection/resource/:slug', to: 'collection_resources#show'
      end
    end
  end

  concern :searchable, Blacklight::Routes::Searchable.new
  concern :exportable, Blacklight::Routes::Exportable.new

  devise_for :users, path: 'auth', controllers: {
    invitations: 'invitations'
  }

  devise_scope :user do
    get 'auth/invitations', to: 'invitations#index'
  end

  resource :profile, only: %i[show edit], controller: 'profile' do
    collection do
      patch 'update', as: 'update'
    end
  end

  resources :repositories, :users, :subjects, :time_periods,
            :features, :projects

  resources :holding_institutions do
    member do
      get 'solr'
    end
  end

  resources :remediation_actions, except: %i[edit update] do
    member do
      post 'perform', to: 'remediation_actions#perform'
      get 'review', to: 'remediation_actions#review'
    end
  end

  resources :item_versions, only: [] do
    member do
      patch :restore
    end
  end

  resources :collections do
    resources :collection_resources
    member do
      post 'reindex_items'
      get 'solr'
    end
  end

  resources :items do
    resources :pages do
      delete :index, on: :collection, action: :destroy_all, as: :destroy_all
    end
    resources :item_versions, only: [] do
      member do
        get :diff, to: 'item_versions#diff'
        patch :rollback, to: 'item_versions#rollback'
      end
    end
    collection do
      delete 'multiple_destroy', constraints: { format: :json }
      post 'xml'
      get 'deleted'
    end
    member do
      get 'copy'
      get 'fulltext'
      get 'solr'
    end
  end
  get '/items/new_from_serial/:serial_id', to: 'items#new_from_serial', as: 'new_item_from_serial'


  resources :batches do
    member do
      post 'recreate', to: 'batches#recreate'
      post 'commit', to: 'batches#commit'
      get 'commit_form', to: 'batches#commit_form'
      get 'import', to: 'batches#import'
      get 'results', to: 'batches#results'
      post 'quick_page_ingest'
    end
    collection do
      get 'select', to: 'batches#select'
    end

    resources :batch_items do
      collection do
        post 'import', to: 'batch_items#import', constraints: { format: :json }
      end
    end

    resources :batch_imports, except: %i[edit update] do
      collection do
        get 'help'
      end
    end
  end

  resources :fulltext_ingests, except: %i[edit update]
  resources :marc_xml_imports, except: %i[edit update] do
    collection do
      delete 'destroy_records'
    end
  end
  resources :page_ingests, except: %i[edit update] do
    member do
      get 'source.json', to: 'page_ingests#source_json', as: 'source_json', defaults: { format: :json }
    end
  end

  get '/reports/:id', to: 'reports#show', as: 'report'
  get '/reports', to: 'reports#index', as: 'reports'

  resource :catalog, only: [:index], controller: 'catalog', constraints: { id: /.*/ } do
    concerns :searchable
    collection do
      get 'facets', to: 'catalog#facets'
    end
    get 'facet_values/:facet_field', to: 'catalog#all_facet_values', as: 'facet_values_csv', constraints: { format: :csv }
  end

  # Constraints used to include format: false, which Rails 6 doesn't like. Deleted for now
  resources :solr_documents, only: [:show], path: '/record', controller: 'catalog', constraints: { id: /.*/ } do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end

  resources :tools, only: %i[index] do
    collection do
      get :csv_import, to: 'tools#csv_import_tool'
      put :csv_import, to: 'tools#csv_import'
      get :csv_template
    end
  end

  mount Blacklight::Engine => '/'
  mount BlacklightAdvancedSearch::Engine => '/'

  # Resque Admin
  resque_constraint = lambda do |request|
    request.env['warden'].authenticate!(scope: :user)
  end
  constraints resque_constraint do
    mount Resque::Server.new => '/resque'
  end

  # Base Paths
  authenticated do
    root to: 'advanced#index', as: :authenticated_root
  end

  root to: redirect('auth/sign_in')

end

app/controllers/catalog_controller.rb
# frozen_string_literal: true

# main blacklight controller
class CatalogController < ApplicationController
  include Blacklight::Catalog
  include BlacklightAdvancedSearch::Controller
  include BlacklightAdvancedSearch::RenderConstraintsOverride
  include MetadataHelper # for rights statement stuff
  include LinkingHelper
  helper BlacklightAdvancedSearch::RenderConstraintsOverride

  layout 'blacklight'

  ADVANCED_FACET_DEFAULT_LIMIT = 300

  authorize_resource class: false

  configure_blacklight do |config|
    config.default_solr_params = {
      qt: 'search',
      fq: ''
    }

    config.add_facet_fields_to_solr_request!

    config.max_per_page = 20000

    config.per_page = [20,50,100,1000]

    config.index.title_field = 'title'
    config.index.display_type_field = 'format'

    config.show.title_field = 'title'
    config.show.display_type_field = 'format'

    config.index.thumbnail_method = :record_thumbnail

    config.add_facet_field 'public_b',                 label: I18n.t('meta.search.facets.public'), helper_method: :boolean_facet_labels
    config.add_facet_field 'display_b',                label: I18n.t('meta.search.facets.display'), helper_method: :boolean_facet_labels
    config.add_facet_field 'dpla_b',                   label: I18n.t('meta.search.facets.dpla'), helper_method: :boolean_facet_labels
    config.add_facet_field 'local_ss',                 label: I18n.t('meta.search.facets.local'), helper_method: :boolean_facet_labels
    config.add_facet_field 'valid_item_b',             label: I18n.t('meta.search.facets.valid_item'), helper_method: :boolean_facet_labels
    config.add_facet_field 'fulltext_present_b',       label: I18n.t('meta.search.facets.fulltext'), helper_method: :boolean_facet_labels
    config.add_facet_field 'provenance_facet',         label: I18n.t('meta.search.facets.provenance'), limit: true
    config.add_facet_field 'publisher_facet',          label: I18n.t('meta.search.facets.publisher'), limit: true
    config.add_facet_field 'creator_facet',            label: I18n.t('meta.search.facets.creator'), limit: true
    config.add_facet_field 'contributor_facet',        label: I18n.t('meta.search.facets.contributor'), limit: true
    config.add_facet_field 'subject_facet',            label: I18n.t('meta.search.facets.subject'), limit: true
    config.add_facet_field 'subject_personal_facet',   label: I18n.t('meta.search.facets.subject_personal'), limit: true
    config.add_facet_field 'year_facet',               label: I18n.t('meta.search.facets.year'), limit: true
    config.add_facet_field 'temporal_facet',           label: I18n.t('meta.search.facets.temporal'), limit: true
    config.add_facet_field 'location_facet',           label: I18n.t('meta.search.facets.location'), limit: true
    config.add_facet_field 'counties_facet',           label: I18n.t('meta.search.facets.county'), limit: true
    config.add_facet_field 'format_facet',             label: I18n.t('meta.search.facets.format'), limit: true
    config.add_facet_field 'rights_facet',             label: I18n.t('meta.search.facets.rights'), limit: true, helper_method: :rights_icon_label
    # config.add_facet_field 'rights_holder_facet'     , label: I18n.t('meta.search.facets.rights_holder'), limit: true
    config.add_facet_field 'relation_facet',           label: I18n.t('meta.search.facets.relation'), limit: true
    config.add_facet_field 'type_facet',               label: I18n.t('meta.search.facets.type'), limit: true
    config.add_facet_field 'medium_facet',             label: I18n.t('meta.search.facets.medium'), limit: true
    config.add_facet_field 'language_facet',           label: I18n.t('meta.search.facets.language'), limit: true
    config.add_facet_field 'repository_name_sms',      label: I18n.t('meta.search.facets.repository'), limit: true
    config.add_facet_field 'collection_titles_sms',    label: I18n.t('meta.search.facets.collection'), limit: true
    config.add_facet_field 'portal_names_sms',         label: I18n.t('meta.search.facets.portals'), limit: true
    config.add_facet_field 'class_name',               label: I18n.t('meta.search.facets.class'), limit: true

    # collection only facets
    config.add_facet_field 'collection_provenance_facet', label: I18n.t('meta.search.facets.collection_only.provenance'), limit: true
    config.add_facet_field 'collection_type_facet',       label: I18n.t('meta.search.facets.collection_only.type'), limit: true
    config.add_facet_field 'collection_spatial_facet',    label: I18n.t('meta.search.facets.collection_only.spatial'), limit: true

    # solr fields to be displayed in the index (search results) view
    #   The ordering of the field names is the order of the display
    config.add_index_field 'score',                       label: I18n.t('meta.search.labels.score'), helper_method: :score_display
    config.add_index_field 'record_id_ss',                label: I18n.t('meta.search.labels.record_id')
    config.add_index_field 'portals_sms',                 label: I18n.t('meta.search.labels.portals'), link_to_search: true
    config.add_index_field 'dcterms_title_display',       label: I18n.t('meta.search.labels.dcterms_title')
    config.add_index_field 'dcterms_description_display', label: I18n.t('meta.search.labels.dcterms_description'), helper_method: :truncate_index
    config.add_index_field 'collection_titles_sms',       label: I18n.t('meta.search.labels.collection'), link_to_search: true
    config.add_index_field 'repository_name_sms',         label: I18n.t('meta.search.labels.repository'), link_to_search: true
    config.add_index_field 'dcterms_identifier_display',  label: I18n.t('meta.search.labels.dcterms_identifier')
    config.add_index_field 'edm_is_shown_at_display',     label: I18n.t('meta.search.labels.edm_is_shown_at'), helper_method: :linkify
    config.add_index_field 'edm_is_shown_by_display',     label: I18n.t('meta.search.labels.edm_is_shown_by'), helper_method: :linkify
    config.add_index_field 'dcterms_creator_display',     label: I18n.t('meta.search.labels.dcterms_creator'), link_to_search: :creator_facet
    config.add_index_field 'dc_format_display',           label: I18n.t('meta.search.labels.dc_format'), link_to_search: :format_facet
    config.add_index_field 'dcterms_spatial_display',     label: I18n.t('meta.search.labels.dcterms_spatial'), link_to_search: :location_facet
    config.add_index_field 'dpla_ss',                     label: I18n.t('meta.search.labels.dpla')
    config.add_index_field 'public_ss',                   label: I18n.t('meta.search.labels.public')
    config.add_index_field 'display_ss',                  label: I18n.t('meta.search.labels.display')
    config.add_index_field 'valid_item_ss',               label: I18n.t('meta.search.labels.valid_item')
    config.add_index_field 'fulltext_present_ss',         label: I18n.t('meta.search.labels.fulltext_present')

    # solr fields to be displayed in the show (single result) view
    #   The ordering of the field names is the order of the display
    config.add_show_field 'slug_ss',                                label: I18n.t('meta.search.labels.item_id')
    config.add_show_field 'record_id_ss',                           label: I18n.t('meta.search.labels.record_id')
    config.add_show_field 'dcterms_title_display',                  label: I18n.t('meta.search.labels.dcterms_title')
    config.add_show_field 'collection_titles_sms',                  label: I18n.t('meta.search.labels.collection'), link_to_search: true
    config.add_show_field 'repository_name_sms',                    label: I18n.t('meta.search.labels.repository'), link_to_search: true
    config.add_show_field 'display_title_display',                  label: I18n.t('meta.search.labels.display_title')
    config.add_show_field 'short_description_display',              label: I18n.t('meta.search.labels.short_description'), helper_method: :linkify_urls
    config.add_show_field 'partner_homepage_url_display',           label: I18n.t('meta.search.labels.partner_homepage_url')
    config.add_show_field 'homepage_text_display',                  label: I18n.t('meta.search.labels.homepage_text')
    config.add_show_field 'dcterms_is_part_of_display',             label: I18n.t('meta.search.labels.dcterms_is_part_of'), helper_method: :regex_linkify
    config.add_show_field 'dcterms_description_display',            label: I18n.t('meta.search.labels.dcterms_description'), helper_method: :linkify_urls
    config.add_show_field 'dc_format_display',                      label: I18n.t('meta.search.labels.dc_format')
    config.add_show_field 'dcterms_identifier_display',             label: I18n.t('meta.search.labels.dcterms_identifier')
    config.add_show_field 'dc_right_display',                       label: I18n.t('meta.search.labels.dc_right'), helper_method: :rights_icon_tag
    config.add_show_field 'dc_date_display',                        label: I18n.t('meta.search.labels.dc_date')
    config.add_show_field 'dc_relation_display',                    label: I18n.t('meta.search.labels.dc_relation')
    config.add_show_field 'dcterms_publisher_display',              label: I18n.t('meta.search.labels.dcterms_publisher')
    config.add_show_field 'dcterms_contributor_display',            label: I18n.t('meta.search.labels.dcterms_contributor')
    config.add_show_field 'dcterms_temporal_display',               label: I18n.t('meta.search.labels.dcterms_temporal')
    config.add_show_field 'dcterms_spatial_display',                label: I18n.t('meta.search.labels.dcterms_spatial'), link_to_search: :location_facet
    config.add_show_field 'dcterms_provenance_display',             label: I18n.t('meta.search.labels.dcterms_provenance')
    config.add_show_field 'new_dcterms_provenance_display',         label: 'New Provenance'
    config.add_show_field 'dcterms_subject_display',                label: I18n.t('meta.search.labels.dcterms_subject'), link_to_search: :subject_facet

app/views/catalog/_constraints.html.erb
<% if query_has_constraints? %>
    <div id="appliedParams" class="clearfix constraints-container">
      <div class="float-right">
        <%=link_to t('blacklight.search.start_over'), start_over_path, class: 'catalog_startOverLink btn btn-sm btn-link', id: 'startOverLink' %>
      </div>
      <span class="constraints-label"><%= t('blacklight.search.filters.title') %></span>
      <%= render_constraints(params) %>
    </div>
<% end %>

app/views/catalog/_constraints_element.html.erb
<%  # local params:
    # label
    # value
    # options =>
    #   :remove => url for a remove constraint link
    #   :classes => array of classes to add to container span
    options ||= {}
%>

<%= render(Blacklight::ConstraintLayoutComponent.new(
  classes: options[:classes],
  label: label,
  value: value,
  remove_path: options[:remove])) %>

app/views/catalog/_edit_record.html.erb
<% klass, id = @document['sunspot_id_ss'].split(' ') %>
<% if klass == 'Item' %>
  <%= link_to t('meta.defaults.actions.edit'), edit_item_path(id) %>
<% elsif klass == 'Collection' %>
  <%= link_to t('meta.defaults.actions.edit'), edit_collection_path(id) %>
<% end %>

app/views/catalog/_facet_limit.html.erb
<ul class="facet-values list-unstyled">
  <% paginator = facet_paginator(facet_field, display_facet) %>
  <%= render_facet_limit_list paginator, facet_field.key %>
  <% unless paginator.last_page? || params[:action] == 'facet' %>
    <%= link_to t("more_#{field_name}_html", scope: 'blacklight.search.facets', default: :more_html, field_name: facet_field.label),
      search_facet_path(id: facet_field.key), class: 'more_facets_link btn btn-outline-secondary' %>
  <% end %>
</ul>

app/views/catalog/_home_text.html.erb
<p>Perform a search to locate Items or use the Manage menu above.</p>

<p>Or, you can use <%= link_to 'Advanced Search', blacklight_advanced_search_engine.advanced_search_path %></p>

app/views/catalog/_index_header_default.html.erb
<%# header bar for doc items in index view -%>
<div class="documentHeader row">
  <%# main title container for doc partial view
      How many bootstrap columns need to be reserved
      for bookmarks control depends on size.
  -%>
  <% document_actions = capture do %>
    <% # bookmark functions for items/docs -%>
    <%= render_index_doc_actions document, wrapping_class: 'index-document-functions col-sm-3 col-lg-2' %>
  <% end %>

  <h3 class="index_title document-title-heading <%= document_actions.present? ? 'col-sm-9 col-lg-10' : 'col-md-12' %>">
    <% if counter = document_counter_with_offset(document_counter) %>
      <span class="document-counter">
        <%= t('blacklight.search.documents.counter', counter: counter) %>
      </span>
    <% end %>

    <% klass, id = document['sunspot_id_ss'].split(' ') %>

    <% if klass == 'Collection' %>
      <span class="label label-info">Collection</span>
    <% end %>

    <% if (current_user.super? || can?(:edit, Item)) && klass == 'Item' %>
        <%= check_box_tag(:action_item, id, false, { id: "select-#{id}", class: 'action-item'}) %>
    <% end %>

    <%= link_to_document document, :title, counter: counter %>

    <%# todo: if user can edit this record... #%>
    <% if current_user.super? || can?(:edit, Item) %>
        <div class="btn-group btn-group-sm float-right">
          <%= link_to(
                  'Edit',
                  url_for(controller: klass.downcase.pluralize, action: :edit, id: id),
                  session_tracking_params(document, counter).merge({class: 'edit-record btn btn-primary'})
              ) %>
          <%= link_to(
                  'Show',
                  url_for(controller: klass.downcase.pluralize, action: :show, id: id),
                  session_tracking_params(document, counter).merge({class: 'show-record btn btn-primary'})
              ) %>
        </div>
    <% end %>
  </h3>

  <%= document_actions %>
</div>

app/views/catalog/_previous_next_doc.html.erb
<% #Using the Bootstrap Pagination class  -%>
<% #DEPRECATED - using id="previousNextDocument" as a selector is deprecated and will be removed in Blacklight 6.0 %>
<div id='previousNextDocument' class='pagination-search-widgets'>
  <% if @previous_document || @next_document %>
      <div class="page_links">
        <%= link_to_previous_document @previous_document %> |

        <%= item_page_entry_info %> |

        <%= link_to_next_document @next_document %>
      </div>
  <% end %>
  <% if current_search_session %>
      <div class="float-right search-widgets">
        <%= link_back_to_catalog class: 'btn btn-link' %>

        <%=link_to t('blacklight.search.start_over'), start_over_path(current_search_session.try(:query_params) || {}), id: 'startOverLink', class: 'btn btn-link' %>
      </div>
  <% end %>
</div>

app/views/catalog/_search_form.html.erb
<div class="basic-search-form">
  <%= bootstrap_form_tag(
      url: search_action_url,
      method: :get,
      role: 'search'
      ) do |f|
  %>

      <%= render_hash_as_hidden_fields(
              search_state.params_for_search.except(:q, :search_field, :qt, :page, :utf8)
          )
      %>

      <%= hidden_field_tag :search_field, search_fields.first.last %>

      <%= f.text_field(
              :q,
              {
                  hide_label: true,
                  label: t('blacklight.search.form.search.label'),
                  value: params[:q],
                  placeholder: t('blacklight.search.form.search.placeholder'),
                  id: 'q',
                  class: 'q search_q',
                  autofocus: should_autofocus_on_search_box?,
                  append: f.submit(t('blacklight.search.form.submit'), class: 'btn btn-primary')
              }
          )
      %>
  <% end %>
</div>

app/views/catalog/_search_header.html.erb
<%# render 'did_you_mean' %>

<%= render 'constraints' %>

<%= render 'sort_and_per_page' %>

app/views/catalog/_search_results.html.erb
<% @page_title = t('blacklight.search.page_title.title', constraints: render_search_to_page_title(params), application_name: application_name) %>

<% content_for(:head) do -%>
  <%= render 'catalog/opensearch_response_metadata', response: @response %>
  <%= rss_feed_link_tag %>
  <%= atom_feed_link_tag %>
  <%= json_api_link_tag %>
<% end %>

<% content_for(:skip_links) do -%>
    <%= link_to t('blacklight.skip_links.first_result'), '#documents', class: 'element-invisible element-focusable rounded-bottom py-2 px-3', data: { turbolinks: 'false' } %>
<% end %>

<% content_for(:container_header) do -%>
  <h1 class="sr-only visually-hidden top-content-title"><%= t('blacklight.search.header') %></h1>

  <%= render 'constraints' %>
<% end %>

<%= render 'search_header' %>

<h2 class="sr-only visually-hidden"><%= t('blacklight.search.search_results') %></h2>

<%- if @response.empty? %>
  <%= render "zero_results" %>
<%- elsif render_grouped_response? %>
  <%= Deprecation.silence(Blacklight::RenderPartialsHelperBehavior) { render_grouped_document_index } %>
<%- else %>
  <%= render_document_index @response.documents %>
<%- end %>

<%= render 'results_pagination' %>

app/views/catalog/all_facets.csv.erb
"<%= "#{@field}_value" %>","<%= "#{@field}_hits" %>"
<% @values.each do |v| %>
"<%= v[:value] %>","<%= v[:hits] %>"
<% end %>

app/views/catalog/facets.html.erb
<% content_for :title do %>
  Facet Browse
<% end %>

<% breadcrumb :facets_browse %>

<ul class="list-group col-md-3">
  <% @facets.each do |f| %>
      <% field = f[:field] %>
      <li class="list-group-item">
        <%= link_to f[:label], facet_catalog_path(field) %>
        <span class="float-right"><%= link_to 'CSV', facet_values_csv_catalog_path(field, format: :csv), class: 'float-right' %></span>
      </li>
  <% end %>
</ul>

app/views/catalog/index.html.erb
<%= content_for :title do %>
    Search
<% end %>

<% breadcrumb :basic_search %>

    <%= render_search_bar  %>

<div class="row">
  <div id="sidebar" class="<%= sidebar_classes %>">
    <%= render 'search_sidebar' %>
  </div>

  <div id="content" class="<%= main_content_classes %>">
    <% unless has_search_parameters? %>
        <%# if there are no input/search related params, display the "home" partial -%>
        <%= render 'home' %>
        <%= render 'shared/sitelinks_search_box' %>
    <% else %>
        <%= render 'search_results' %>
    <% end %>
  </div>
</div>

app/views/catalog/show.html.erb
<% if current_search_session %>
  <div id="appliedParams" class="clearfix constraints-container">
    <%= render 'start_over' %>
    <%= link_back_to_catalog class: 'btn btn-outline-secondary' %>
  </div>
<% end %>

<div class="btn-group float-right">
  <%= link_to 'Edit', edit_record_path(@document), class: 'btn btn-primary' %>
  <%= link_to 'Show', show_record_path(@document), class: 'btn btn-primary' %>
</div>
<div class="container">
  <div class="row">
    <div class="col-sm-8 col-md-9">
    <%= render 'show_main_content' %>
    </div>
    <div class="col-sm-4 col-md-3 mt-5">
      <%= record_thumbnail(@document,nil) %>
    </div>
  </div>
</div>
<% content_for(:sidebar) do %>
  <%= render_document_sidebar_partial @document %>
<% end %>